### ISSUE TITLE
Tiers and special mods

### ISSUE THREAD

**Issue by raphaelrieuhelft** [doomeer/kalandralang#23]
Currently the following recipe fails with the error message `Error: don't know how to compute tiers for mod group: "Intelligence"` , presumably because the essence mod isn't actually in the mod pool, so it can't be found in the sorted list computed by `Item.mod_tier`.

```
buy "Metadata/Items/Armours/Helmets/HelmetInt11"
essence_of_spite
if tier "Intelligence" <= 2
then gain 1 alt
```

In this case it's not clear to me what the output of `tier` should be (the essence mod is not equivalent to either T1 or T2 on helmets). Maybe returning 999 for modifiers outside the mod pool would be fine, but also, computing the tier of the essence mod is never needed (the recipe could simply check that the mod is still there in case of e.g. annuls), so maybe it's even OK to fail here with a clearer error message.

**Comment by doomeer** [comment]
Indeed, the error message is confusing. I pushed a commit to change it to:
```
don't know how to compute tier for "IntelligenceEssence7" in group "Intelligence"
```
which I think is more clear.

I agree with you that it may be ok to fail here. There may be cases where it is a bit annoying though, such as after an annul where the essence mod may or may not be here anymore, resulting in either an error or 999. I think it is important to return 999 when there is no intelligence mod at all, to support `tier "Intelligence" <= 3` without having to write `has_group "Intelligence" and tier "Intelligence" <= 3` all the time (`has_group` doesn't exist yet :p). Returning 999 for an essence mod would feel wrong because we do have a very good tier of Intelligence.

I guess another option could be to consider deafening essence mods as being tier 1? This is what Craft of Exile does.

**Comment by raphaelrieuhelft** [comment]
If that's easy to do, sure, I think considering them tier 1 is OK. What I meant with my annul comment is that every recipe that may want to check that the essence mod is still there after using an annul can simply use `has IntelligenceEssence7` instead of using `tier`.

**Comment by doomeer** [comment]
I'm not sure how easy it would be. I guess it would mean splitting the mod group in two sets: essence mods and non-essence mods (there is an `is_essence_only` flag if I remember correctly so this is easy) and then just sorting those two sets independently. So `tier` on an essence mod would mean "the tier relatively to other essence mods".

I agree that since we can already write `has "TheEssenceMod"` this is probably not very high priority.

**Comment by AR-234** [comment]
but setting essence mods to t1 is alright I think, because these mods are forced on anyway and take the slot of the equal mod..

**Comment by rbardou** [comment]
I pushed a couple of commits that give tiers to essence mods.
- If a modifier is essence-only, Kalandralang looks at the level of the essence. For instance, Deafening mods have tier 1, Shrieking mods have tier 2, etc.
- But if the modifier is not essence-only, it uses the regular sorting mechanism. I tested on helmets and it gives T1 for deafening essence of anger. There may be odd cases where the result is not satisfying though…

In any case, the example posted by @raphaelrieuhelft in his original message now works :)

**Comment by doomeer** [comment]
I pushed a couple of commits that give tiers to essence mods.
- If a modifier is essence-only, Kalandralang looks at the level of the essence. For instance, Deafening mods have tier 1, Shrieking mods have tier 2, etc.
- But if the modifier is not essence-only, it uses the regular sorting mechanism. I tested on helmets and it gives T1 for deafening essence of anger. There may be odd cases where the result is not satisfying though…

In any case, the example posted by @raphaelrieuhelft in his original message now works :)
