### ISSUE TITLE
[Feature Request] "is_base <base_type>" predicate

### ISSUE THREAD

**Issue by haggys22** [doomeer/kalandralang#28]
When recombining two different bases, e.g. Imbued Wand and Prophecy Wand, there is no way to check if the resulting item has the indended base.

# Proposal
Introduce a new predicate, e.g. `is_base`, on current item. Usage: `is_base <base_type>`. Evaluates to true if the current item has the `<base_type>` base.

# Example
```
.restart:
# Imbued Wand
buy "Metadata/Items/Weapons/OneHandWeapons/Wands/Wand13"
set_aside

# Prophecy Wand
buy "Metadata/Items/Weapons/OneHandWeapons/Wands/Wand16"

if not is_base "Metadata/Items/Weapons/OneHandWeapons/Wands/Wand13" then goto .restart
show # current item is an Imbued Wand
```

**Comment by rbardou** [comment]
Believe it or not, I also had implemented this a few days ago and forgot to push. Looks like working with recombinators lead us to the exact same conclusions :D

Actually I had (after some hesitation) named my predicate `base_is` instead of `is_base`. Since your input seems to show that `is_base` is more natural, I changed it to `is_base` before pushing.

Now go transfer some fractured mods to better bases :D

**Comment by doomeer** [comment]
Believe it or not, I also had implemented this a few days ago and forgot to push. Looks like working with recombinators lead us to the exact same conclusions :D

Actually I had (after some hesitation) named my predicate `base_is` instead of `is_base`. Since your input seems to show that `is_base` is more natural, I changed it to `is_base` before pushing.

Now go transfer some fractured mods to better bases :D

**Comment by haggys22** [comment]
Finally I can simulate crafting a 500 pDPS wand using recombinators :D

I settled with `is_base` because it aligns with `has_mod` or `has_group`.
